### ISSUE TITLE
Add support for projects that use Jinja2 templating

### ISSUE THREAD

**Issue by toolness** [18F/django-uswds-forms#11]
I'm not sure if any 18F projects use Jinja2, but since Django itself supports Jinja2 out-of-the-box now, maybe we should too?

**Comment by toolness** [comment]
Jinja2 has a guide on [switching over from Django](http://jinja.pocoo.org/docs/2.9/switching/#django) and it looks like this should be pretty straightforward.

**Comment by jacobian** [comment]
👍  if we're going 1.11+ only, then we should use Jinja 100% - it's a ton faster, especially for purposes like this where we're potential rendering dozens of templates.

**Comment by toolness** [comment]
Ok @jacobian I just added initial support!  Here's the docs:

http://django-uswds-forms.readthedocs.io/en/latest/quickstart.html#jinja2-setup-optional

Also, the [example gallery](https://django-uswds-forms.app.cloud.gov/) entries now have an additional accordion on them, which allows you to see the Jinja2 source for an example (in addition to the Django template source, and the Python view).

The example app test suite also runs through all the examples and makes sure that the HTML rendered by the Django template version is identical to that of the Jinja2 version.

Anyhow, any feedback is appreciated.
