### ISSUE TITLE
Settle on a strategy for USWDS support

### ISSUE THREAD

**Issue by toolness** [18F/django-uswds-forms#2]
So I originally thought this was going to be a straightforward "rip out the code from CALC and plop it in a python package" job, but I'm now realizing there's a few decisions we made on CALC that made perfect sense at the time, but might not be ideal for this package.

These decisions had to do with two different approaches for making our forms look like USWDS.

## Approach 1: Style Django's default markup to look like USWDS

Basically, for CALC there were a lot of places where we just "renamed" or "copied" some of USWDS' classes so they matched with Django's default classes. For example, rather than trying to get Django to change the class of its help text to `usa-form-hint`, we just styled the `helptext` class (Django's default class name for help text) so it looked like `usa-form-hint`.

In a similar vein, I think we just styled Django's default form error markup so that it looked like USWDS's, rather than trying to change Django's output so it matched USWDS.

This approach is still viable but has a few downsides:

* It results in CSS bloat.
* It means that any changes one might want to make to USWDS's look-and-feel *might* actually need to be made against multiple selectors (particularly if different parts of the project are styling things through different style name "families").  I guess clever use of SASS might be able to obviate this.
* It increases the likelihood of styling mismatches as the project upgrades to new versions of USWDS. (Again, this could potentially be obviated through clever use of SASS, but should a project need SASS just so their Django forms can stay in-sync with USWDS styling?)

## Approach 2: Modify Django forms HTML output to be USWDS-friendly

This means, for example, that Django forms should never render `class="helptext"`; instead, they should only render `class="usa-form-hint"`.

I'm not sure how hard this will be, but I think it might be easier in the post-Django 1.11 world, where widgets are rendered via (extremely) modularized, overrideable templates rather than hard-to-modify Python classes that paste strings together.

That said, there's an additional wrinkle introduced if we want to do things this way, because we now have *two* ways of providing USWDS-style functionality:

* **Opt-in**: we make a "parallel" set of USWDS-friendly widgets that generate USWDS-friendly markup. This is our current approach with `UswdsRadioSelect` and `UswdsCheckbox`.

* **Override**: we "monkeypatch" Django's default widgets to just work with USWDS by default.  This is particularly easy to do with Django 1.11's new template-based widgets, because we can just make templates with the right file name and path and let the mechanics of Django's template loader take care of the rest. See the docs on [overriding built-in widget templates](https://docs.djangoproject.com/en/1.11/ref/forms/renderers/#overriding-built-in-widget-templates) for more details.

Overriding might be more convenient for developers, but it also might have unintended consequences for e.g. parts of a site that *don't* want to look like USWDS.

## Conclusion

So CALC actually used *both* approaches, depending on context. For checkboxes and radios, we took Approach 2, making special widget classes that `Form` instances had to opt-in to in order to work. But for other things like displaying errors, we took Approach 1, rolling with the markup Django provided and trying to style it so it looked USWDS-ish.

Sometimes, depending on the context, I think Approach 2 was very difficult or impossible to do with Django, because it simply didn't have APIs or extension points through which we could easily change its default markup.  That said, we were on Django 1.8/1.9 back then, and as mentioned earlier, Django 1.11's new forms API *should* make Approach 2 easier. This is definitely the case with USWDS radios and checkboxes, at least: making them in Django 1.8 required reading a bunch of undocumented Django code and figuring out how to hack it, while implementing the same widgets in Django 1.11 involved making a single template and pointing to it through trivial widget subclasses.

@hbillings, @jacobian, or anyone else who's interested--thoughts on this are welcome!

**Comment by jacobian** [comment]
There's at least one other option to consider, which is to build on top of a third-party forms templating library, like [floppyforms](https://github.com/gregmuellegger/django-floppyforms). 

The upside of this approach is a fairly clean API (e.g. `{% form myform using "uswds_forms/layout.html" %}` is how this could look with Floppy). The downside is that there are several competing form layout libraries, and by choosing one we'd foisting that choice upon anyone downstream, which is probably less than ideal. Another downside is that it's fairly likely that these sorts of features will end up in Django eventually: the template stuff in 1.11 seem to point fairly strongly towards future improvements.

I don't much like this option, but I'm including it for completeness.

**Comment by jacobian** [comment]
So, investigating further, I think I have another option that might be the best. There's middle-ground option between the "opt-in" and the "monkeypatch" approach: provide a custom form renderer: https://docs.djangoproject.com/en/1.11/ref/forms/renderers/#the-low-level-render-api. This would allow:

- opt-in on a per-form basis, in Python code, by doing something like `f = SomeForm(renderer=USWDSFormRenderer)`

- opt-in for the entire site by setting the `FORM_RENDERER` setting to something like `uswds_forms.USWDSFormRenderer`

- re-using individual templates in your own custom renderer by creating a subclass of `USWDSFormRenderer` and overriding specific templates.

The only downside here is that this would be 1.11+ only, but honestly I'm OK with that. Upgrading isn't super-hard for older projects, and my guess is that only newer stuff is going to use this library anyway. I think forcing people who want to use this to use an up-to-date Django isn't a huge problem (and a nice incentive to upgrade :wink:)

**Comment by toolness** [comment]
Nice! We should definitely explore that... right now I am playing with the opt-in approach in #4 (I'm also dropping support for Django < 1.11 in it and have no qualms w/ it). I think we might be able to lift some of the stuff I'm doing there into a separate `UswdsFormRenderer` class.

**Comment by toolness** [comment]
Hmm, so I looked into making a separate renderer class but it seems a bit *too* low-level for our needs, from what I could tell.

From what I understand, form renderers are responsible for taking a *template name* and a *context* and converting that into HTML.  Creating our own renderer, especially one based on the [`TemplatesSetting`](https://docs.djangoproject.com/en/1.11/ref/forms/renderers/#templatessetting) renderer, seems like it'd be useful in allowing us to transparently "swap out" one template for another, which would be particularly useful for the radios and checkboxes, where `<input>` and `<label>` elements are in slightly different order, but it doesn't seem like it'd address some of our other use cases:

* Sometimes we don't actually need to modify anything at the template layer, but rather the *context* that ultimately gets passed into the template. This is the case with the `usa-unstyled-list` class that we apply to the list of items in [`UswdsRadioSelect`](http://django-uswds-forms.readthedocs.io/en/latest/reference.html#uswds_forms.UswdsRadioSelect) and [`UswdsCheckboxSelectMultiple`](http://django-uswds-forms.readthedocs.io/en/latest/reference.html#uswds_forms.UswdsCheckboxSelectMultiple) widgets, for instance. And it's the case with setting [`Form.required_css_class`](https://docs.djangoproject.com/en/1.11/ref/forms/api/#django.forms.Form.required_css_class), which is actually just a core Django 1.11 forms API feature.

* Sometimes the problem lies outside a template system entirely, which is the case with the [`UswdsErrorList`](http://django-uswds-forms.readthedocs.io/en/latest/reference.html#uswds_forms.UswdsErrorList) class. It's actually *impossible* to address this kind of functionality purely by specifying a different form renderer, as far as I can tell.

* I have no idea how we'd implement the functionality provided by high-level "macros" like the [`{% fieldset %}`](http://django-uswds-forms.readthedocs.io/en/latest/reference.html#fieldset) template tag,  the [`fieldset()`](http://django-uswds-forms.readthedocs.io/en/latest/reference.html#uswds_forms.fieldset) jinja2 helper, or the [`UswdsForm.as_fieldsets()`](http://django-uswds-forms.readthedocs.io/en/latest/reference.html#uswds_forms.UswdsForm.as_fieldsets)  convenience method purely through a form renderer.

So, given these wrinkles, I decided to not implement a form renderer subclass. We can certainly revisit it in the future if I made the wrong decision, though.

With that said, I guess the work I've done on this project over the past several days, which was originally explorational, has ended up taking **Approach 2**.  There isn't currently any single "quick and easy" way to get any form to look like USWDS, unfortunately, but I'm hoping that the [example gallery](https://django-uswds-forms.app.cloud.gov/) combined with the [API reference](http://django-uswds-forms.readthedocs.io/en/latest/reference.html) makes it straightforward for people to adopt the USWDS style in their forms, while also keeping things flexible enough for users to customize the system to their own particular needs.

So, I'm closing this issue for now, but we can re-open it later if we decide that I made the wrong call. 😄
